src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 * fields={"user_email"},
 * message="l'email que vous avez indiqué est déja utilisé !")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_nom;
/**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $username;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_password;
/**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $password;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_adresse;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $user_tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_sex;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $user_datenaissance;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $user_cin;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $user_matriculecnss;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Employe", inversedBy="utilisateur")
     */
    private $User;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Patient", inversedBy="utilisateur")
     */
    private $UserPatient;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserNom(): ?string
    {
        return $this->user_nom;
    }
    public function setUserNom(?string $user_nom): self
    {
        $this->user_nom = $user_nom;

        return $this;
    }
    public function getUsername(): ?string
    {
        return $this->username;
    }
    public function setUsername(?string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getUserPrenom(): ?string
    {
        return $this->user_prenom;
    }

    public function setUserPrenom(?string $user_prenom): self
    {
        $this->user_prenom = $user_prenom;

        return $this;
    }

    public function getUserEmail(): ?string
    {
        return $this->user_email;
    }

    public function setUserEmail(?string $user_email): self
    {
        $this->user_email = $user_email;

        return $this;
    }

    public function getUserPassword(): ?string
    {
        return $this->user_password;
    }

    public function setUserPassword(?string $user_password): self
    {
        $this->user_password = $user_password;

        return $this;
    }
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }
    public function getUserAdresse(): ?string
    {
        return $this->user_adresse;
    }

    public function setUserAdresse(?string $user_adresse): self
    {
        $this->user_adresse = $user_adresse;

        return $this;
    }

    public function getUserTel(): ?int
    {
        return $this->user_tel;
    }

    public function setUserTel(?int $user_tel): self
    {
        $this->user_tel = $user_tel;

        return $this;
    }

    public function getUserSex(): ?string
    {
        return $this->user_sex;
    }

    public function setUserSex(?string $user_sex): self
    {
        $this->user_sex = $user_sex;

        return $this;
    }

    public function getUserDatenaissance(): ?\DateTimeInterface
    {
        return $this->user_datenaissance;
    }

    public function setUserDatenaissance(?\DateTimeInterface $user_datenaissance): self
    {
        $this->user_datenaissance = $user_datenaissance;

        return $this;
    }

    public function getUserCin(): ?int
    {
        return $this->user_cin;
    }

    public function setUserCin(?int $user_cin): self
    {
        $this->user_cin = $user_cin;

        return $this;
    }

    public function getUserMatriculecnss(): ?string
    {
        return $this->user_matriculecnss;
    }

    public function setUserMatriculecnss(?string $user_matriculecnss): self
    {
        $this->user_matriculecnss = $user_matriculecnss;

        return $this;
    }

    public function getRoles(): array
    {
     $roles= $this->roles;
       $roles[]= 'ROLE_USER';
       return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

     return $this;
    }
    public function resetRoles()
    {
        $this->roles = [];
    }
    public function eraseCredentials(){}
    public function getSalt(){}

    public function getUser(): ?Employe
    {
        return $this->User;
    }

    public function setUser(?Employe $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getUserPatient(): ?Patient
    {
        return $this->UserPatient;
    }

    public function setUserPatient(?Patient $UserPatient): self
    {
        $this->UserPatient = $UserPatient;

        return $this;
    }
  

}

src/Controller/UserController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use App\Entity\User;
use App\Entity\Role;
use App\Form\RegistrationType;
//use Doctrine\ORM\EntityManagerInterface;
use App\Repository\UserRepository;
use App\Repository\RoleRepository;
use Symfony\Component\HttpFoundation;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class UserController extends Controller
{
    /**
     * @Route("/admin", name="user")
     */
    public function index()
    {
      
        $repo=$this->getDoctrine()->getRepository(User::class);
        $users=$repo->findAll();
  
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
            'users'=>$users
        ]);
    }
    /**
     * @Route("/home",name="userhome")
     */
    public function home(){
        return $this->render('user/home.html.twig');
    }
      /**
     * @Route("/login",name="connexion")
     */
    public function login(){
        return $this->render('user/login.html.twig');
    }
      /**
     * @Route("/deconnexion",name="logout")
     */
    public function logout(){
        return $this->render('user/login.html.twig');
    }
    /**
     * @Route("/inscription",name="user/inscription")
     *  @Route("/modifieuser/{id}",name="user/showuser")
     */
    public function registration(Request $request,UserPasswordEncoderInterface $encoder,SessionInterface $session, UserInterface $user){
        $user=new User();
        $manger = $this->getDoctrine()->getManager();
  
        if(!$user){
            $user=new User();
        }
             
$session1 = $this->session=$session;
$this->session->set('id', 'id');
$foo = $this->session->get('id');
     //  var_dump($session1);exit;

        $form=$this->createForm(RegistrationType::class,$user);
        $form->handleRequest($request);
    if($form->isSubmitted() && $form->isValid()){
        $hash=$encoder->encodePassword($user,$user->getPassword());
      
        if(!$user->getId()){
            $user->setUserDatenaissance(new \DateTime());
        }
          $user->setPassword($hash);
      $user->setUserDatenaissance(new \DateTime());
    //  $user->setRoles(['ROLE_ADMIN']);
      $manger->persist($user);
      $manger->flush();
      return $this->redirectToRoute('connexion');
    }
        return $this->render('user/add.html.twig',['formuser'=>$form->createView(),'editMode'=>$user->getId()!==null]);
    }
  
    /**
     * @Route("/adduser",name="user/add")
     * @Route("/modifieuse/{id}",name="user/showuserd")
     */
    public function form(User $user =null,Request $request){
        $manger = $this->getDoctrine()->getManager();
       $role=new Role();
    
            
        if(!$user){
            $user=new User();
        }
        $form=$this->createFormBuilder($user)
        ->add('usernom', TextType::class, [
            'attr' => [
                'placeholder' => "Nom",
                'class'=>"form-control"
            ]
        ])
        ->add('userprenom', TextType::class, [
            'attr' => [
                'placeholder' => "Prénom",
                'class'=>"form-control"
            ]
        ])
        ->add('useremail', TextType::class, [
            'attr' => [
                'placeholder' => "Email",
                'class'=>"form-control"
            ]
        ])
        ->add('userpassword', TextType::class, [
            'attr' => [
                'placeholder' => "password",
                'class'=>"form-control"
            ]
        ])
        ->add('usercin', TextType::class, [
            'attr' => [
                'placeholder' => "CIN",
                'class'=>"form-control"
            ]
        ])
        ->add('usermatriculecnss', TextType::class, [
            'attr' => [
                'placeholder' => "Matricule CNSS",
                'class'=>"form-control"
            ]
        ])
        ->add('usersex', ChoiceType::class, [
            'choices'  => [
                'Etat' => null,
                'Femme' => 'Femme',
                'Homme' => "Homme",
            ],
            'attr' => [
                'placeholder' => "Sex",
                'class'=>"form-control"
            ]
        ])
        ->add('role', EntityType::class, [
            'class' => Role::class,
            'query_builder' => function (RoleRepository $er) {
                $qb = $er->createQueryBuilder($rolenom="rolenom",$id=null);
                return $qb->select('r')
                ->from(Role::class,'r');
                //->where('r.id = ?1');
               // ->orderBy('u.name', 'ASC');
             
            },
            'choice_label' => 'role_nom',
            ])
            
     //   ->add('Ajouter',SubmitType::class,['label'=>'Enregistrer'])
        ->getForm();
        $form->handleRequest($request);
    if($form->isSubmitted() && $form->isValid()){
        if(!$user->getId()){
            $user->setRoleDateCreation(new \DateTime());
        }
      $user->setRoleDateCreation(new \DateTime());
      $manger->persist($user);
      $manger->flush();
  return $this->redirectToRoute('user/showuser',['id'=>$user->getId()]);
    }
                return $this->render('user/add.html.twig',['formuser'=>$form->createView(),'editMode'=>$user->getId()!==null]);
    }
   
/**
     * @Route("/patient/{id}",name="show")
     */
    public function show($id){
        $repo=$this->getDoctrine()->getRepository(User::class);
        $users=$repo->find($id);
        return $this->render('user/show.html.twig',['users'=>$users]); 
    }
  /*  public function setDefaultOptions(OptionsResolverInterface $resolver){
       
$resolver->setDefaults(array('data_class'=>''));
       
    }*/

}

templates/user/add.html.twig
{% extends 'Template.html.twig' %}

{% block title %}Hello UserCotrUController!{% endblock %}
{% form_theme formuser 'bootstrap_4_layout.html.twig' %}
{% block body %}

 <!-- Input addon -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title"> {%if  editMode %} Modifier {% else %} Ajouter {% endif %}</h3>
              </div>
           
              {{form_start(formuser)}}
              
          <!--    <div class="card-body">
                
                 <h4>Nom User</h4>

                <div class="input-group">
               {{form_widget(formuser.user_nom)}}
                 
                </div>--!>
                 
   

                   <br>
                  <div class="input-group">
                  {%if  editMode %}  <button type="submit" class="btn btn-success">Modifier</button>
                  {% else %}  
                  <button type="submit" class="btn btn-success">Ajouter</button>
                  {% endif %}
             
    
            </div>
{{form_end(formuser)}}
             
            </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'Template.html.twig' %}

{% block title %}Hello UserCotrUController!{% endblock %}

{% block body %}

  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- DataTables -->
  <link rel="stylesheet" href=""{{ asset ('build/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css')}}">
  <link rel="stylesheet" href=""{{ asset ('build/plugins/datatables-responsive/css/responsive.bootstrap4.min.css')}}">
<!-- /.card -->

          <div class="card">
             <div class="card-header">
              <h3 class="card-title">Gestion Administrateur</h3>
            </div>
             <div class="card-header">
            <a href="{{ path('user/inscription')}}">Ajouter</a>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>Nom</th>
                  <th>Prenom</th>
                  <th>Date De naissance</th>
                  <th>Sex</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>{%for user in users %}
                <tr>
                
                  <td>{{user.usernom}}</td>
                  <td>{{user.userprenom}}
                  </td>
                  <td>{{user.userdatenaissance|date('d/m/y')}}</td>
                  <td> {{user.userSex}}</td>
                  <td><a href="{{ path('user/showuser',{'id':user.id})}}"class="btn btn-primary">Modifier</a></td>
                
                </tr>  {% endfor %}
               
             
                </tbody>
                <tfoot>
                <tr>
                   <th>Nom</th>
                  <th>Prenom</th>
                  <th>Date De naissance</th>
                  <th>Sex</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>

          <script src="{{ asset ('build/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{ asset ('build/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- DataTables -->
<script src="{{ asset ('build/plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{ asset ('build/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{ asset ('build/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
<script src="{{ asset ('build/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset ('build/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset ('build/dist/js/demo.js')}}"></script>
<!-- page script -->
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true,
      "autoWidth": false,
    });
  
  });
</script>
{% endblock %}

templates/user/login.html.twig
{% extends 'Template.html.twig' %}
{% block body %}
            <!-- Horizontal Form -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Connexion </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form action="{{path('connexion')}}" method="post" class="form-horizontal">
                <div class="card-body">
                  <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-10">
                      <input type="email" name="_username" class="form-control" id="inputEmail3" placeholder="Adresse Email">
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-10">
                      <input type="password" name="_password" class="form-control" id="inputPassword3" placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="offset-sm-2 col-sm-10">
                      <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="exampleCheck2">
                        <label class="form-check-label" for="exampleCheck2">Remember me</label>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-success">Connexion</button>
                  <button type="submit" class="btn btn-default float-right">Cancel</button>
                </div>
                <!-- /.card-footer -->
              </form>
            </div>
         {% endblock %}

templates/user/show.html.twig
{% extends 'Template.html.twig' %}

{% block title %}Hello UserCotrUController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
 <!-- Input addon -->
            <div class="card card-info">
              <div class="card-header">
                <h3 class="card-title">Input Addon</h3>
              </div>
              <div class="card-body">
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text">@</span>
                  </div>
                  <input type="text" class="form-control" placeholder="Username">
                </div>

                <div class="input-group mb-3">
                  <input type="text" class="form-control">
                  <div class="input-group-append">
                    <span class="input-group-text">.00</span>
                  </div>
                </div>

                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">$</span>
                  </div>
                  <input type="text" class="form-control">
                  <div class="input-group-append">
                    <span class="input-group-text">.00</span>
                  </div>
                </div>

                <h4>With icons</h4>

                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                  </div>
                  <input type="email" class="form-control" placeholder="Email">
                </div>

                <div class="input-group mb-3">
                  <input type="text" class="form-control">
                  <div class="input-group-append">
                    <span class="input-group-text"><i class="fas fa-check"></i></span>
                  </div>
                </div>

                <div class="input-group">
                  <div class="input-group-prepend">
                    <span class="input-group-text">
                      <i class="fas fa-dollar-sign"></i>
                    </span>
                  </div>
                  <input type="text" class="form-control">
                  <div class="input-group-append">
                    <div class="input-group-text"><i class="fas fa-ambulance"></i></div>
                  </div>
                </div>

                <h5 class="mt-4 mb-2">With checkbox and radio inputs</h5>

                <div class="row">
                  <div class="col-lg-6">
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text">
                          <input type="checkbox">
                        </span>
                      </div>
                      <input type="text" class="form-control">
                    </div>
                    <!-- /input-group -->
                  </div>
                  <!-- /.col-lg-6 -->
                  <div class="col-lg-6">
                    <div class="input-group">
                      <div class="input-group-prepend">
                        <span class="input-group-text"><input type="radio"></span>
                      </div>
                      <input type="text" class="form-control">
                    </div>
                    <!-- /input-group -->
                  </div>
                  <!-- /.col-lg-6 -->
                </div>
                <!-- /.row -->

                <h5 class="mt-4 mb-2">With buttons</h5>

                <p>Large: <code>.input-group.input-group-lg</code></p>

                <div class="input-group input-group-lg mb-3">
                  <div class="input-group-prepend">
                    <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
                      Action
                    </button>
                    <ul class="dropdown-menu">
                      <li class="dropdown-item"><a href="#">Action</a></li>
                      <li class="dropdown-item"><a href="#">Another action</a></li>
                      <li class="dropdown-item"><a href="#">Something else here</a></li>
                      <li class="dropdown-divider"></li>
                      <li class="dropdown-item"><a href="#">Separated link</a></li>
                    </ul>
                  </div>
                  <!-- /btn-group -->
                  <input type="text" class="form-control">
                </div>
                <!-- /input-group -->

                <p>Normal</p>
                <div class="input-group mb-3">
                  <div class="input-group-prepend">
                    <button type="button" class="btn btn-danger">Action</button>
                  </div>
                  <!-- /btn-group -->
                  <input type="text" class="form-control">
                </div>
                <!-- /input-group -->

                <p>Small <code>.input-group.input-group-sm</code></p>
                <div class="input-group input-group-sm">
                  <input type="text" class="form-control">
                  <span class="input-group-append">
                    <button type="button" class="btn btn-info btn-flat">Go!</button>
                  </span>
                </div>
                <!-- /input-group -->
              </div>
              <!-- /.card-body -->
            </div>
{% endblock %}